---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.ingressEntryPointPort }}
      targetPort: 8080

---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      {{ .Values.ingressEntryPointName }}:
        port: {{ .Values.ingressEntryPointPort }}
        expose:
          default: true
        exposedPort: {{ .Values.ingressEntryPointPort }}
