haStateEntityId: "input_select.inkyframe_screen"
image: "example.url"
appName: "inkyframe-images"
secretName: "inkyframe-secrets"
gcsSecretFileLocation: "./gcs_key.json"
registrySecretName: "registrySecrets"
namespace: "microservices"
servicePort: "8081"
cloudStorageBucketName: "example-bucket"
haImageUrl: "example.prod.svc.cluster.local"
